### ISSUE TITLE
Local Development

### ISSUE THREAD

**Issue by jagathks** [CloutFeed/mobileApp#144]
Any documentation or api links that we use to develop on our local machine?
Also i see in code it requires "CLOUTFEED_API_KEY" where can we get that for local development?

Some initial guidance/document is much appreciated.

**Comment by jagathks** [comment]
can someone answer pls!!
@unnamed92
@AhmadMazaal 
@iamuddeshya

**Comment by RHatem** [comment]
In the README file there is an explanation how to start the project on you local device. Currently, there is no documentation for the code and we are far from releasing one. Soon, we will release code guidelines and some tips to contribute but not a detailed documentation of the code.

However, if you have any questions we are very happy to answer these at anytime. You can join our Discord server for faster communication.

https://discord.gg/pg5wtWVGcy

Regarding the CLOUTFEED_API_KEY, this is our API secret and it is just accessible for internal developers for security reasons. It is not required for most of the project parts though.
